TRIGgerA:STATe off,
TRIGgerA:STATe idle,
TRIGgerA:STATe arm,
TRIGgerA:STATe run,
TRIGgerA:MODE FINite,
TRIGgerA:MODE INFinite,
TRIGgerA:INput USB,
TRIGgerA:INput EXTernal,
TRIGgerA:INput TRIGgerB,
TRIGgerA:INput TRIGgerC,
TRIGgerA:INput BUTTon,
TRIGgerA:RATE <freq>,// TRIGgerA:RATE <freq>,
TRIGgerA:PERIod <time>,// TRIGgerA:PERIod <time>,
TRIGgerA:SIZE <size>,// TRIGgerA:SIZE <size>,
TRIGgerB:STATe off,
TRIGgerB:STATe idle,
TRIGgerB:STATe arm,
TRIGgerB:STATe run,
TRIGgerB:MODE FINite,
TRIGgerB:MODE INFinite,
TRIGgerB:INput USB,
TRIGgerB:INput EXTernal,
TRIGgerB:INput TRIGgerC,
TRIGgerB:INput BUTTon,
TRIGgerB:RATE <freq> , // TRIGgerB:RATE <freq> ,
TRIGgerB:PERIod <time> , // TRIGgerB:PERIod <time> ,
TRIGgerB:SIZE <size> , // TRIGgerB:SIZE <size> ,
TRIGgerC:STATe off,
TRIGgerC:STATe idle,
TRIGgerC:STATe arm,
TRIGgerC:STATe run,
TRIGgerC:MODE FINite,
TRIGgerC:MODE INFinite,
TRIGgerC:INput USB,
TRIGgerC:INput EXTernal,
TRIGgerC:INput BUTTon,
TRIGgerC:RATE <freq> ,// TRIGgerC:RATE <freq> ,
TRIGgerC:PERIod <time> ,// TRIGgerC:PERIod <time> ,
TRIGgerC:SIZE <size> ,// TRIGgerC:SIZE <size> ,
SOURceA:MODE TRIGgered,
SOURceA:MODE DETached,
SOURceA:MODE SINGleshot,
SOURceA:FUNCtion:SHAPe RAMP ,
SOURceA:FUNCtion:SHAPe ARBitrary ,
SOURceA:RAMP:RATIO <ratio> , // SOURceA:RAMP:RATIO <ratio> ,
SOURceA:ARBitrary:READ ,
SOURceA:ARBitrary:LOAD ,
SOURceA:ARBitrary:VALUe <val> , // SOURceA:ARBitrary:VALUe <val> ,
SOURceA:FUNCtion:AMPlitude <ampl>, // SOURceA:FUNCtion:AMPlitude <ampl>,
SOURceA:FUNCtion:OFFset <offs>, // SOURceA:FUNCtion:OFFset <offs>,
SOURceA:FUNCtion:HIgh <high> , // SOURceA:FUNCtion:HIgh <high> ,
SOURceA:FUNCtion:LOw <low> , // SOURceA:FUNCtion:LOw <low> ,
SOURceA:FUNCtion:DELay <steps> , // SOURceA:FUNCtion:DELay <steps> ,
SOURceA:VOLTage:LEVel <volts> , // SOURceA:VOLTage:LEVel <volts> ,
SOURceA:PULSe:WIDth <time>, // SOURceA:PULSe:WIDth <time>,
SOURceB:MODE TRIGgered,
SOURceB:MODE DETached,
SOURceB:MODE SINGleshot,
SOURceB:FUNCtion:SHAPe RAMP ,
SOURceB:FUNCtion:SHAPe ARBitrary ,
SOURceB:RAMP:RATIO <ratio> , // SOURceB:RAMP:RATIO <ratio> ,
SOURceB:ARBitrary:READ ,
SOURceB:ARBitrary:LOAD ,
SOURceB:ARBitrary:VALUe <val> , // SOURceB:ARBitrary:VALUe <val> ,
SOURceB:FUNCtion:AMPlitude <ampl>, // SOURceB:FUNCtion:AMPlitude <ampl>,
SOURceB:FUNCtion:OFFset <offs>, // SOURceB:FUNCtion:OFFset <offs>,
SOURceB:FUNCtion:HIgh <high> , // SOURceB:FUNCtion:HIgh <high> ,
SOURceB:FUNCtion:LOw <low> , // SOURceB:FUNCtion:LOw <low> ,
SOURceB:FUNCtion:DELay <steps> , // SOURceB:FUNCtion:DELay <steps> ,
SOURceB:VOLTage:LEVel <volts> , // SOURceB:VOLTage:LEVel <volts> ,
SOURceB:PULSe:WIDth <time>, // SOURceB:PULSe:WIDth <time>,
ROUTe:CLOSe GAL ,
ROUTe:CLOSe SLD ,
ROUTe:CLOSe AIM ,
ROUTe:CLOSe CAM ,
ROUTe:OPEN GAL ,
ROUTe:OPEN SLD ,
ROUTe:OPEN AIM ,
ROUTe:OPEN CAM ,
ROUTe:STATE? GAL ,
ROUTe:STATE? SLD ,
ROUTe:STATE? AIM ,
ROUTe:STATE? CAM ,
I2C::MODE off ,
I2C::MODE USB ,
I2C::MODE SLAVeaction,
I2C::WRITe <val> , // I2C::WRITe <val> ,
I2C::READ,
UART:MODE off ,
UART:MODE USB ,
UART:MODE SLAVeaction,
UART:WRITe <val> , // UART:WRITe <val> ,
UART:READ,
DIGIO:MODE off ,
DIGIO:MODE in ,
DIGIO:MODE out ,
DIGIO:WRIte <val> , // DIGIO:WRIte <val> ,
DIGIO:READ ,
ANAlog0:MODE off ,
ANAlog0:MODE USB ,
ANAlog0:MODE trigA ,
ANAlog0:MODE trigB ,
ANAlog0:MODE trigC ,
ANAlog0:READ,
ANAlog1:MODE off ,
ANAlog1:MODE USB ,
ANAlog1:MODE trigA ,
ANAlog1:MODE trigB ,
ANAlog1:MODE trigC ,
ANAlog1:READ,
ANAlog2:MODE off ,
ANAlog2:MODE USB ,
ANAlog2:MODE trigA ,
ANAlog2:MODE trigB ,
ANAlog2:MODE trigC ,
ANAlog2:READ,
ANAlog3:MODE off ,
ANAlog3:MODE USB ,
ANAlog3:MODE trigA ,
ANAlog3:MODE trigB ,
ANAlog3:MODE trigC ,
ANAlog3:READ,
SYStem:CRC16 OFF ,
SYStem:CRC16 ON ,
SYStem:POWerdown ,
SYStem:LISt ,
SYStem:RESEt ,
SYStem:RESTart ,
SYStem:VERBose OFF,
SYStem:VERBose ON ,
SYStem:WATchdog OFF,
SYStem:WATchdog ON,
SYStem:WATchdog <time> , // SYStem:WATchdog <time> ,
